name: build-windows-exe

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set UTF-8 code page
        shell: pwsh
        run: chcp 65001

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install pyinstaller openpyxl et_xmlfile
          }

      - name: Build executable
        shell: pwsh
        run: python build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExcelConsolidator-win
          path: dist/**
          if-no-files-found: error
